### ISSUE TITLE
Total Unrealized PNL doesn't match the number in binance app

### ISSUE THREAD

**Issue by aumanusorn** [ecoppen/futuresboard#39]
Total Unrealized PNL doesn't match the number in binance app

**Comment by ecoppen** [comment]
The Binance App/Website will be accurate all the time whereas futuresboard will only be accurate at the time it scrapes which by default is every 5 minutes. 

How far out is it at the moment it scrapes?

**Comment by ecoppen** [comment]
Feel free to reopen if the issue continues with the answer to the above ^

**Comment by ecoppen** [comment]
If you have large orders open that are in a volatile market, this number can change rapidly within a second or 10 seconds, let alone 5 minutes. For example the balance is $1.1 away from the one on Binance which shows more trades have occurred since the last update. You can try and reduce the time the scraper activates within the configuration file to see if this keeps it closer in line.

**Comment by aumanusorn** [comment]
I'm afraid that the IP will be banned. What's the lowest time that I can config?

**Comment by ecoppen** [comment]
The scraper will pause if it's close to hitting the IP limit. Lowest time is every minute, so 60 seconds.
